.\" pkgman-path(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-PATH 1
.Os pkgman @VERSION@
.\" ==================================================================
.Sh NAME
.Nm pkgman-path
.Nd print path to package source
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm path
.Ar pkgname
.\" ==================================================================
.Sh DESCRIPTION
Print path to package source location in the packages sources
directories.
.\" ==================================================================
.Sh EXIT STATUS
0 if path found, 255 otherwise.
.\" vim: cc=72 tw=70
.\" End of file.
