.\" pkgman-search(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-SEARCH 1
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgman-search
.Nd search the packages sources directories for package name
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm search
.Op Fl v | Fl vv
.Op Fl \-path
.Op Fl \-regex
.Ar expr
.\" ==================================================================
.Sh DESCRIPTION
Search the packages sources directories for
.Ar expr
in packages' name.
It looks in all directories specified in
.Pa /etc/pkgman.conf
as
.Dq pkgsrcdir
argument.
.Pp
The options are as follows:
.Bl -tag -width XXXXXXX
.It Fl v
Show package version in the listing.
.It Fl vv
Show package version and description in the listing.
.It Fl \-path
Show package source path in the listing.
.It Fl \-regex
Interpret
.Ar expr
as regular expression.
.It Ar expr
Search names for
.Ar expr ,
where the expression may be the string or regex in
.Xr regex 3
format.
.El
.\" ==================================================================
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Success.
.It 255
Nothing found.
.El
.\" vim: cc=72 tw=70
.\" End of file.
