.\" pkgman-lock(8) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-LOCK 8
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgman-lock
.Nd lock the package(s)
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm lock
.Ar pkgname ...
.\" ==================================================================
.Sh DESCRIPTION
Lock the packages and do not update them in a
.Xr pkgman-sysup 8
operation.
.\" ==================================================================
.Sh FILES
.Bl -tag -width Ds
.It Pa /var/lib/pkg/locked
Database of locked packages.
.El
.\" ==================================================================
.Sh EXIT STATUS
0 if successfully locked, 255 otherwise.
.\" vim: cc=72 tw=70
.\" End of file.
