.\" pkgman-info(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-INFO 1
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgman-info
.Nd print package information
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm info
.Op Fl v | vv
.Ar pkgname
.\" ==================================================================
.Sh DESCRIPTION
Print available information for a package.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl v , Fl vv
Print also the README file if exists.
.El
.\" ==================================================================
.Sh ENVIRONMENT
If the following environment variable exists it will be utilized by
.Xr pkgman 1 :
.Bl -tag -width Ds
.It Ev PAGER
If the package source directory has a README file, and the
.Fl v
or
.Fl vv
option is set then
.Nm
will try to open it using a
.Ev PAGER .
If
.Ev PAGER
is unset, then
.Nm
prints the README to stdout.
.El
.\" ==================================================================
.Sh EXIT STATUS
0 if success, 255 otherwise.
.\" vim: cc=72 tw=70
.\" End of file.
