.\" pkgman-list-locked(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-LIST-LOCKED 1
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgman-list-locked
.Nd print list of locked packages
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm list-locked
.Op Fl v Ns | Ns Fl vv
.Op Fl \-path
.\" ==================================================================
.Sh DESCRIPTION
Print list of locked packages.
.Dq Locked
are packages that will not update while performing a system update.
.Pp
The options are as follows:
.Bl -tag -width XXXXXX
.It Fl v
Show package version in the listing.
.It Fl vv
Show package version and description in the listing.
.It Fl \-path
Show package source path in the listing.
.El
.\" ==================================================================
.Sh FILES
.Bl -tag -width Ds
.It Pa /var/lib/pkg/locked
Database of locked packages.
.El
.\" vim: cc=72 tw=70
.\" End of file.
