.\" pkgman-isinst(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 9, 2023
.Dt PKGMAN-ISINST 1
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgman-isinst
.Nd print whether packages are installed or not
.\" ==================================================================
.Sh SYNOPSIS
.Nm pkgman
.Cm isinst
.Ar pkgname ...
.\" ==================================================================
.Sh DESCRIPTION
Print whether packages are installed or not.
.\" ==================================================================
.Sh EXIT STATUS
0 if installed, 255 otherwise.
.\" vim: cc=72 tw=70
.\" End of file.
