pkgman-list-orphans(8) "version #VERSION#" "Package Manager Manual"

# NAME

pkgman-list-orphans - print list of orphan packages

# SYNOPSIS

*pkgman* list-orphans [-v|-vv] [--path]

# DESCRIPTION

Print list of orphan packages. "Orphans" are packages without packages depending
on them.

# OPTIONS

[[ *-v*
:< Show version in the listing.
|  *-vv*
:  Show version and description in the listing.
|  *--path*
:  Show package' source path in the listing.

; End of file.
