name: Lint CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck

#   - name: Check man pages for errors (requires mandoc)
#     run: cd man && make lint

#   FIXME: fix completion script for shellcheck warning
#   - name: Check completion scripts for errors
#     run: cd completion && make lint

# End of file.
